americanexpress/one-app

__tests__/server/utils/watchLocalModules.spec.js
src/server/utils/watchLocalModules.js

after generating a module, running `npm run watch:build` and serving it locally in One App, the follow error would appear:
```
log: Failed to load Holocron module at [one-app-dev-cdn-url]/static/modules/my-module/1.0.0/yeehaw.node.js
log: Error: only absolute urls are supported
```
this fix replaces the static [one-app-dev-cdn-url] string and replaces it with the actual ip and port when pulling from the module map. 
Note: The module still loaded successfully before this fix - this is specifically to mitigate the error in the console.

fix(utils): replace watchLocalModules cdn-url string to be ip/port

---

README.md

Rather than use `frank-lloyd-root` in the quick start section, revised the section to use the new `generator-one-app-module` library to scaffold a custom root module so users better understand the process of creating and serving a module.

docs(readme): add new quick start section

---

README.md

old npx command was faulty. The correct command (for our scoped library) is `npx -p yo -p @americanexpress/generator-one-app-module -- yo @americanexpress/one-app-module`

docs(readme): update generator command

---

__tests__/server/middleware/__snapshots__/csp.spec.js.snap
__tests__/server/middleware/csp.spec.js
docs/api/modules/App-Configuration.md
src/server/middleware/csp.js

moves logic to add IP and `localhost` to csp when `NODE_ENV=development` from root module to One App.
One thing to note: root module _must_ have csp directives (`script-src`, `connect-src`) defined already in order for ip and localhost to be added. One App only adds the values to `script-src` and `connect-src` if they're pre-existing directives.
Feedback on the explanation in the docs is much appreciated.

feat(csp): add local development domains to csp

---

__tests__/server/utils/__snapshots__/stateConfig.spec.js.snap
__tests__/server/utils/stateConfig.spec.js
docs/api/modules/App-Configuration.md
prod-sample/sample-modules/frank-lloyd-root/0.0.0/src/config.js
prod-sample/sample-modules/picky-frank/0.0.0/src/components/PickyFrank.jsx
src/server/utils/stateConfig.js

This allows the provideStateConfig to accept more than an object
or a string.
Closes #20

feat(stateConfig): make state config more flexible

---

README.md

Added NODE_ENV as it is required for the one-app-generator to create a module

docs(readme): update readme for generator

---

docs/recipes/Mocking-API-Calls.md

After the dev.endpoints file format was updated the corresponding doc was not. This change is to update that doc.
Documentation for mocking api calls is wrong as currently written.
Made sure md parsed well in github
Improves their lives as the docs are now accurate.

use correct dev.endpoints file format in mocking api calls recipe

---

__tests__/server/middleware/__snapshots__/csp.spec.js.snap
__tests__/server/middleware/csp.spec.js
__tests__/server/utils/stateConfig.spec.js
src/server/middleware/csp.js
src/server/utils/stateConfig.js

- FIx csp directives to include dev proxy server port.
- Fix path joining in state config.
Solves csp directives not including dev proxy server port.
Solves incorrect double slash `//` in path naming.  
Includes tests to validate desired behavior.
Dev proxy server port should appear on csp directives, allowing proper testing with parrot.
Allows defining paths in mock endpoints with leading or no leading slash.

Bug fixes for mocking data

---

__tests__/integration/one-app.spec.js
prod-sample/sample-modules/healthy-frank/0.0.0/src/components/HealthyFrank.jsx
prod-sample/sample-modules/ssr-frank/0.0.0/src/components/SsrFrank.jsx

Healthy frank needed a checkup.
change onHover to onMouseOver
Locally by running healthy-frank and integration tests
None

fix(healthyFrank): change onHover for onMouseOver

---

__tests__/integration/one-app.spec.js

Removes a flaky integration test where the `{ active: { state: 'activated' } }` but often comes back as `registration.active.state === 'activating'`.
None

test(integration/pwa): inconsistent active state string

---

docs/api/modules/App-Configuration.md

Adding an advisory on using `provideStateConfig` and server specific values in docs.
Warn not to expose sensitive data and prevent leaks.

docs(api/app-config): add caution on state config

---

package.json

Correct changelog output
locally
Remove manual correction when releasing

fix(release/change-log): remove -e added

---

prod-sample/sample-modules/cultured-frankie/0.0.0/src/components/CulturedFrankie.jsx
prod-sample/sample-modules/cultured-frankie/0.0.1/src/components/CulturedFrankie.jsx
prod-sample/sample-modules/frank-lloyd-root/0.0.0/src/components/FrankLloydRoot.jsx
prod-sample/sample-modules/frank-lloyd-root/0.0.1/src/components/FrankLloydRoot.jsx
prod-sample/sample-modules/frank-lloyd-root/0.0.2/src/components/FrankLloydRoot.jsx
prod-sample/sample-modules/franks-burgers/0.0.0/src/components/index.jsx
prod-sample/sample-modules/needy-frank/0.0.0/src/components/NeedyFrank.jsx
prod-sample/sample-modules/needy-frank/0.0.1/src/components/NeedyFrank.jsx
prod-sample/sample-modules/preview-frank/0.0.0/src/components/PreviewFrank.jsx
prod-sample/sample-modules/preview-frank/0.0.0/src/duck.js
prod-sample/sample-modules/vitruvius-franklin/0.0.0/src/components/VitruviusFranklin.jsx
prod-sample/sample-modules/vitruvius-franklin/0.0.1/src/components/VitruviusFranklin.jsx

Update sample modules to use the updated Holocron API.
Removed `holocronModule` in favor of `Module.holocron` for configuring modules.
Keep sample modules up to date.
Test suite.
Sample modules are up to date.

refactor(sample-modules): holocron config

---

package.json
scripts/build-service-workers.js
scripts/watch-server.js

Fixes a bug with `start:watch` not able to load the service worker scripts and fails.
Added `scripts/watch-server.js` which watches the server, service worker scripts and rebuilds when either are updated.
Fix `start:watch` `npm` script.
Manual testing during development.
Working local development when using `start:watch` script.

fix(scripts/watch): ensure missing sw scripts

---

.github/dependabot.yml

Changes weekly dependabot runs to monthly. Furthermore, I removed `open-pull-requests-limit` that was set to 10 to revert it back to the default 5.
Decrease the amount of dependabot PRs
N/A

chore(dependabot): update dependabot config

---

__tests__/server/middleware/healthCheck.spec.js
src/server/middleware/healthCheck.js

health check was using an old api of `pidusage`.
fixes failing health check.
locally by starting one-app and calling `/im-up` on port 3005. before was failing, now returning expected stats

fix(metrics): health check

---

src/server/middleware/pwa/config.js

Fixes a bug when the config is not set.
The config relied on pre-processing before creating it - recent addition removed this pre-processing when validation was moved.
Locally
Fixes bug for users using service worker

fix(pwa): reset config when not supplied

---

__tests__/server/utils/watchLocalModules.spec.js
src/server/utils/watchLocalModules.js

This ensures that `chokidar` waits for the the file to be stable before firing `change` event.
- https://github.com/paulmillr/chokidar#performance see awaitWriteFinish
> in some cases some change events will be emitted while the file is being written. In some cases, especially when watching for large files there will be a need to wait for the write operation to finish before responding to a file creation or modification
One App crashing when large modules are rebuilt
used an oversized root module, was able to produce crashing of one-app 3/4 attemps. After change could not reproduce crash. 
Should no longer crash when large modules are rebuilt.

fix(watchLocalModules): wait for change to finish

---

__tests__/integration/one-app.spec.js
__tests__/server/ssrServer.spec.js
docs/recipes/Making-An-Api-Call.md
src/server/ssrServer.js

post parameters are available in `req.body` only when request `content-type` is `application/json`. There is no way to handle default encoding method.
Feature to enable form post with default encoding method `application/x-www-form-urlencoded`
There is a need for the clients to use form post for sharing information on to the application. This feature is already available in lower version of one-app.
Tested it locally by posting parameters, we could verify all of the post parameters in `req.body`
NA

feat(ssrServer): enable urlencoded post data

---

__tests__/server/listen.spec.js
src/server/listen.js

fix(security): specify min TLS version

---

README.md
docs/api/README.md
docs/api/server/Routes.md
docs/recipes/README.md
docs/recipes/Reporting-Client-Errors.md

docs(error-reporting): add reporting client errors recipe

---

__tests__/server/middleware/createRequestHtmlFragment.spec.js
__tests__/server/utils/createCircuitBreaker.spec.js
src/server/utils/createCircuitBreaker.js

Fix typo of the circuit breaker “function” input.

fix(typo): circuit breaker “function” input

---

package.json

Adds `npm run test:lockfile` to the `pre-commit` script of Husky.
So that the test runs before committing.

chore(precommit): add lockfile lint test to pre-commit script

---

docs/recipes/One-App-Runner.md

New recipe to develop locally with One App Runner

docs(one-app-runner): add new recipe

---

__tests__/server/middleware/clientErrorLogger.spec.js
package-lock.json
package.json
src/server/middleware/clientErrorLogger.js

Update One App Ducks to 4.2.1 to fix the `clientErrorLogger` attempting to spread a stringified object https://github.com/americanexpress/one-app-ducks/pull/20
Also added the `util.inspect` to `console.error` to log deep objects up to a maximum of 10 levels
Unit tests
Tested making an API call to the client error logger to confirm expected functionality

fix(clientErrorLogger): format console error message

---

docs/recipes/Making-An-Api-Call.md
docs/recipes/Module-Composition.md
docs/recipes/Post-To-Modules.md
docs/recipes/README.md

docs(recipes/making-an-api-call): update

---

__tests__/server/utils/createCircuitBreaker.spec.js
src/server/utils/createCircuitBreaker.js

Increase the circuit breaker healthcheck interval from 500ms to 5s.
500ms is a little excessive and could be more frequent than the actual configured threshold
Unit tests

feat(createCircuitBreaker): increase healthcheck interval to 5s

---

package-lock.json
package.json

update to one-app-dev-cdn which includes handling of promise created when fetching remote module map during development
Better error message when fetching invalid module map
locally using valid and invalid module maps.

fix(one-app-dev-cdn): handle uncaught promise

---

__tests__/server/utils/logging/__snapshots__/serverMiddleware.spec.js.snap
__tests__/server/utils/logging/serverMiddleware.spec.js
src/server/utils/logging/serverMiddleware.js

fix duplicate request logs. 
Every request is currently being logged twice because as of Node 12 the 'close' event is fired in every request regardless. 
> Indicates that the the response is completed, or its underlying connection was terminated prematurely (before the response completion).
https://nodejs.org/docs/latest-v12.x/api/http.html#http_event_close_1
Unit tests and locally by watching for duplicate request logs

fix(requestLog): only log on close

---

__tests__/client/__snapshots__/prerender.spec.js.snap
__tests__/client/prerender.spec.js
src/client/prerender.js

I'm proposing that when One App runs `initClient`  that it only remove helmet scripts from the body and will no longer append those scripts to the head of the html doc. Appending the helmet scripts to the head will be done by `Helmet`, because `Helmet` will add the scripts to the head whether it runs before or after `moveHelmetScripts`.
This PR changes `moveHelmetScripts` so that 1) it only queries the DOM for helmet scripts in the body rather than in the entire document, 2) no longer appends scripts to the head. 
When One App middleware runs `sendHtml` on the server and creates an html doc it appends helmet scripts from the request to the html body. When the app is initialized on the client, the `moveHelmetScripts` function is invoked and it retrieves all scripts in the html doc, removes …

fix(helmet): fixes race condition with react-helmet

---

docs/overview/Getting-Started.md

I've updated the links on Getting-Started.md from lower-case paths to corresponding upper-case paths to match the doc files.
GitHub wasn't happy with the links that did not match the exact case of the markdown file names. These links were showing up as 404 pages.
I've verified the links on this doc on my branch.
None

docs(overview): fix links in Getting-Started.md

---

__tests__/server/middleware/csp.spec.js
src/server/middleware/csp.js

The changes made in #636 are breaking due to the script nonce being added to the initial response, even if the environment variable is enabled and it is being correctly suppressed from the CSP header.
The middleware that prepares the HTML response already includes a check to not apply the script nonce if it isn't populated, so we just need to ensure that the nonce is never populated if inline scripts are enabled in dev, rather than simply suppressing it in the header. I've moved the code applying up slightly inside the conditional blocks that run either in production, or if the env var isn't set.
I tested this feature using a root module, and it only occurs if the app's root module is a prod build and not being served, and so overlooked this scenario.
Bugfix for #636
This bug only occurs …

fix(csp): remove script nonce if inline scripts are disabled

---

__tests__/server/middleware/addFrameOptionsHeader.spec.js
package-lock.json
src/server/middleware/addFrameOptionsHeader.js

remove "https://" from referrer when looking for frame-ancestors match
fix
test suide

fix(addFrameOptions): strict csp domain now matches

---

README.md

Updates a 404'ing link in the README.
The [one-app-runner](https://github.com/americanexpress/one-app/blob/main/guides/One-App-Runner.md) link in the [README](https://github.com/americanexpress/one-app) 404's, as it is missing the `docs/` slug.
I was revisiting One App for the first time in a while and found this while setting up.
The link works now.
The README link should work as expected.

docs(readme): fix one app runner guide link in readme

---

.github/workflows/release-step-3_automatic_prepare-docker-tags.yml
.github/workflows/release-step-4_automatic_docker-prod-build-and-publish.yml
.github/workflows/release-step-5_automatic_docker-dev-build-and-publish.yml
RELEASE.md

This PR allows control over the docker meta tag (such as `latest` `next` etc)
1. Three workflows (Release 3, 4, and 5) now accept a required choice of `latest`, `next`, or `do_not_tag`.
- Although Release 3 does not use this value, it will pass it to Release 4. Since Release 3 is the 'entrypoint' for releasing arbitrary tags, Release 3 must receive this value and pass it on.
2. The `Normalize meta tag` step of Release 3, 4, and 5 will determine the value, in this order:
- If the previous workflow passed in a value, that will be used
- If the user has specified a value, that will be used
- For automatic runs on the main branch, the value will be `latest`
- For automatic runs on any other branch the value will be `do_not_tag`
3. The value is used while tagging and pushing the docker image …

chore(workflow): allow control of docker meta tag

---

.github/workflows/release-step-4_automatic_docker-prod-build-and-publish.yml
.github/workflows/release-step-5_automatic_docker-dev-build-and-publish.yml

When publishing a `next` version, do not tag as `major` or `major.minor` so that people who are targeting those don't get automatically move to pre-release

chore(workflows): only tag major and major.minor for latest

---

Dockerfile

Bump the node version used by One App to 16.16.0
This is a security patch
https://github.com/nodejs/node/releases/tag/v16.16.0
Info on the vulnerability:
https://mta.openssl.org/pipermail/openssl-announce/2022-July/000232.html
integration tests

fix(node): bump node to 16.16.0 for security patch

---

package-lock.json
package.json

Updates one-app-ducks to v4.4.0 which includes a feature that allows users to provide a URL to fetch their language packs from instead of using the language packs generated by one-app-bundler
This enables engineers to use a CMS or other tooling to provide their language packs with the benefits gotten through using the built-in language pack feature, namely server side caching
Updated cultured-frankie to point to an instance of json-server and loaded it as the root module. Manually tested out using its language switching feature watching the network tab and server logs, and of course there are new unit tests in one-app-ducks.
No impact for developers not using the new feature.

feat(intl): allow custom URLs for language packs

---

CHANGELOG.md
one-app-statics/package.json
package-lock.json
package.json

Minor release for v6.1.0
Automated release process is failing due to message in commit a0fc9ed928b90c56c179080067c9b4908fbe4a9e.
This PR will get releases back on track once tagged.
1. `npm run release:standard-version -- -r minor` 
2. `npm run release:changelog`
3. `git commit -a --amend -n`
4. `git tag v6.1.0`
5. `npm run release`
6. validated new version was 6.1.1
7. reverted v6.1.1 release commit and deleted v6.1.0 tag
Continue new releases of One App

chore(release): 6.1.0

---

__tests__/server/plugins/reactHtml/createRequestHtmlFragment.spec.jsx
__tests__/server/plugins/reactHtml/createRequestStore.spec.js
__tests__/server/plugins/reactHtml/index.spec.jsx
__tests__/server/plugins/reactHtml/staticErrorPage.spec.jsx
src/server/plugins/reactHtml/createRequestHtmlFragment.jsx
src/server/plugins/reactHtml/createRequestStore.js
src/server/plugins/reactHtml/index.jsx
src/server/plugins/reactHtml/staticErrorPage.jsx

Fastify plugin that takes care of creating the redux store, converting react into html, and responding
This is part of the ExpressJS -> Fastify migration. The plugin allows us to simply reply with `reply.sendHtml()` from any route
Manual, Unit Testing, Integration Testing

[REFACTOR] React to HTML plugin

---

__tests__/server/plugins/addCacheHeaders.spec.js
__tests__/server/plugins/addFrameOptionsHeader.spec.js
__tests__/server/plugins/addSecurityHeaders.spec.js
__tests__/server/plugins/conditionallyAllowCors.spec.js
__tests__/server/plugins/csp.spec.js
__tests__/server/plugins/ensureCorrelationId.spec.js
__tests__/server/plugins/forwardedHeaderParser.spec.js
__tests__/server/plugins/setAppVersionHeader.spec.js
src/server/plugins/addCacheHeaders.js
src/server/plugins/addFrameOptionsHeader.js
src/server/plugins/addSecurityHeaders.js
src/server/plugins/conditionallyAllowCors.js
src/server/plugins/csp.js
src/server/plugins/ensureCorrelationId.js
src/server/plugins/forwardedHeaderParser.js
src/server/plugins/healthCheck.js
src/server/plugins/setAppVersionHeader.js

Converted small ExpressJS middlewares into Fastify plugins. These are considered small since have relatively small code and they are (almost) completely abstract
By converting ExpressJS middlewares into Fastify plugins, we can migrate routes from Express to Fastify to improve app's performance
Unit testing

Converted small middlewares into plugins

---

package-lock.json
package.json

This brings a new opt-in performance enhancement of preventing the holocronModuleWrapper from calling 'toJS' on module state: https://github.com/americanexpress/holocron/blob/main/packages/holocron/docs/api/README.md#options-object
locally run against modules
N/A

chore(holocron): take latest holocron

---

package-lock.json
package.json

This brings a new opt-in performance enhancement of preventing the holocronModuleWrapper from calling 'toJS' on module state: https://github.com/americanexpress/holocron/blob/main/packages/holocron/docs/api/README.md#options-object
locally run against modules
N/A

chore(holocron): take latest holocron for v5

---

.github/workflows/bundle-size.yml

preactjs/compressed-size-action wants node 16, default is node 18
This is marking PR's as failed as the check fails with a message about node 18 not being supported
N/A

chore(workflow): lock node major version

---

__tests__/integration/one-app.spec.js
__tests__/server/utils/__snapshots__/loadModules.spec.jsx.snap
__tests__/server/utils/loadModules.spec.jsx
package-lock.json
package.json
src/server/utils/loadModules.js

currently any module which does not get loaded correctly is re-required on every module map poll.
This change limits fetching and parsing modules to one round per change in the module map.
limit unnecessary calls to require-from-string which consumes memory.
None

fix(load-modules): unnecessary calls to updateModuleRegistry

---

.eslintrc.json
__tests__/server/config/env/runTime.spec.js
__tests__/server/middleware/createRequestHtmlFragment.spec.js
__tests__/server/utils/createCircuitBreaker.spec.js
docs/api/modules/Loading-Data.md
package-lock.json
package.json
src/server/middleware/createRequestHtmlFragment.jsx
src/server/utils/createCircuitBreaker.js

**This is a backport of #927 for one-app@5**
Depends on americanexpress/holocron#137.
With this change developers can throw an error from their `loadModuleData` function that will abort `composeModules` and trigger a redirect.
This is a performance optimization for the redirect use case.
Unit tests

feat(createRequestHtmlFragment): allow modules to trigger a redirect from loadModuleData (v5)

---

.eslintrc.json
__tests__/server/config/env/runTime.spec.js
__tests__/server/plugins/reactHtml/createRequestHtmlFragment.spec.jsx
__tests__/server/utils/createCircuitBreaker.spec.js
docs/api/modules/Loading-Data.md
package-lock.json
package.json
src/server/plugins/reactHtml/createRequestHtmlFragment.jsx
src/server/utils/createCircuitBreaker.js

Depends on americanexpress/holocron#137.
With this change developers can throw an error from their `loadModuleData` function that will abort `composeModules` and trigger a redirect.
This is a performance optimization for the redirect use case.
Unit tests

feat(middleware): trigger a redirect from loadModuleData

---

__tests__/integration/one-app.spec.js
__tests__/server/utils/__snapshots__/loadModules.spec.jsx.snap
__tests__/server/utils/loadModules.spec.jsx
package-lock.json
package.json
src/server/utils/loadModules.js

This is a backport of https://github.com/americanexpress/one-app/pull/939 for One App v5
currently any module which does not get loaded correctly is re-required on every module map poll.
This change limits fetching and parsing modules to one round per change in the module map.
limit unnecessary calls to require-from-string which consumes memory.
Unit and integration test.

fix(load-modules): unnecessary calls to updateModuleRegistry (v5)

---

__mocks__/node-fetch.js
__tests__/server/utils/devCdnFactory.spec.js
src/server/utils/devCdnFactory.js

devCdn was using old `got` api instead of the newer `node-fetch` API.
This broke local development when fetching a remote module map

fix(devCdn): requests were not using node-fetch API

---

package-lock.json
package.json

Bump holocron to 1.6.0.
This introduces a new API to holocron to allow you to pass mapStateToProps to holocron.

feat(holocron): allow mapStateToProps to be passed to holocron

---

docs/api/modules/App-Configuration.md
docs/api/server/Environment-Variables.md
docs/guides/Internationalizing-Your-Module.md
src/server/plugins/conditionallyAllowCors.js

This change corrects a few typos in documentation files
Noticed a typo and decided to correct 
Testing is not required for this type of change

Fix typos in documentation

---

__tests__/server/utils/__snapshots__/pollModuleMap.spec.js.snap
__tests__/server/utils/loadModules.spec.jsx
__tests__/server/utils/pollModuleMap.spec.js
package-lock.json
package.json
src/server/utils/loadModules.js
src/server/utils/pollModuleMap.js

Consuming the latest Holocron version which includes rejected module updates.
Makes use of rejected modules to provide additional logs and reset the module map poll time.
Additional PR should follow which adds the rejected module information in the metrics.
After Holocron resiliency update one-app no longer reset when a module is rejected. The error is also logged only once which reduces the visibility of the error.  
The aim of this is to improve DX when modules rejected. 
Locally and test suite.

Update holocron - provide rejected modules

---

__tests__/server/utils/__snapshots__/pollModuleMap.spec.js.snap
__tests__/server/utils/loadModules.spec.jsx
__tests__/server/utils/pollModuleMap.spec.js
package-lock.json
package.json
src/server/utils/loadModules.js
src/server/utils/pollModuleMap.js

backport for https://github.com/americanexpress/one-app/pull/962

feat(pollModuleMap): holocron provide rejected externals

---

__tests__/server/utils/logging/__snapshots__/production-formatter.spec.js.snap
src/server/utils/logging/production-formatter.js

This PR removes the `"nodeFramework":"fastify"` key & value in log entries.
Libraries and implementation can be tracked by the application version. Rather than an extra key in each log entry the `package-lock.json` for the tagged version, or the `node_modules` in the published image/running container can be inspected.
Existing tests, updated the snapshots.
I believe very little, if any. Perhaps slightly less storage space required, though not a high concern given the verbosity of the entries.

fix(server): remove extra nodeFramework key from log entries

---

.prettierrc
__tests__/integration/__snapshots__/one-app.spec.js.snap
__tests__/server/metrics/summaries.spec.js
src/server/metrics/ssr.js
src/server/metrics/summaries.js
src/server/middleware/createRequestHtmlFragment.jsx

Add a `oneapp_ssr_react_rendering_seconds` summary metric split by `renderMethodName` label.
Mirror of #991 for 5.x
Server-Side Rendering (SSR) can be resource intensive. It is useful to operators to know a bit more about the time taken to render the HTML via React.
Run locally, comparing manual timers (`process.hrtime.bigint`) to the values visible in `http://localhost:3005/metrics`.
DevOps has more telemetry to track server utilization to aid SSR efficiency in modules and possible server scaling.

feat(server): add SSR React rendering summary metric

---

.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml

test with Node.js 18.x but before 18.16.0
This will need to be reverted when the bug is resolved and released in a new version.
unit tests are affected by a bug: https://github.com/nodejs/node/issues/47563
GitHub workflow, so can't run locally :S
but did run the semver syntax through https://semver.npmjs.com/ with lodash via `^4 < 4.17`
PRs should have less false-positives.

chore(workflows): on-pr-and-trunk_one-app-unit-and-lint-tests exclude 18.16.0

---

docs/guides/Post-To-Modules.md

Fixes #902 
AFAICT There's no special handling for the request body like passing it as props to your module.  It's just parsed by https://github.com/fastify/fastify-formbody and present on the request object and can be handled with `buildInitialState`.
Doc update.
Corrects wrong documentation.

docs(post-to-modules): correct request body info

---

src/universal/utils/transit.js

We noticed a memory leak happening where if non-immutable data was put into the store, transit-js would cache all the keys for that non-immutable data. This cache persisted across calls, and would grow indefinitely. 
The solution is to use transit-js directly, and disable the cache. unfortunately transit-immutable-js does not allow you to pass options to transit-js, so we have to add handles manually.
memory leaks are bad
Tested independently and unit tested

fix(memoryLeak): disable cache for transitjs

---

.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml

Remove Node.js 12.x and 14.x from the PR testing matrix; 16.x remains.
12.x and 14.x are EOL
PR checks
Developers may need to change the version of Node.js they have installed to run this directly on their machines. However, they should  have done this already to minimize the delta between their machines and the image artifact.

chore(workflows): remove Node.js 12.x & 14.x from on-pr-and-trunk_one-app-unit-and-lint-tests

---

__tests__/server/utils/logging/fastifyPlugin.spec.js
src/server/utils/logging/fastifyPlugin.js

if configureRequestLog is not provided by root module, request logs are not being logged.
re enable request logs
Test suite and locally

fix(configureRequestLog): use default when configured with undefined

---

__tests__/integration/__snapshots__/one-app.spec.js.snap
__tests__/integration/one-app.spec.js
__tests__/server/ssrServer-requests.spec.js
__tests__/server/ssrServer.spec.js
src/server/ssrServer.js

enable `application/csp-report` content type support.
Also included alternative pattern for testing `ssrServer`, this should reduce the reliance on integration tests as well as provide a slightly less mock heavy tests.
Currently CSP reports are failing due to unsupported content type.
Locally, unit and integration tests.

fix(csp-report): add application/csp-report content type support

---

Dockerfile

Bump the node version used by One App to 16.20.1
This is a security patch
https://github.com/nodejs/node/releases/tag/v16.20.1
> The 16.x release line of Node.js is vulnerable to 4 medium severity issues, and 1 high severity issues [sic].
https://nodejs.org/en/blog/vulnerability/june-2023-security-releases
GitHub workflow will run
transparent header parsing fix, so no impact expected

fix(node): bump node to 16.20.1 for security patches

---

__tests__/server/utils/tracer.spec.js
src/server/utils/tracer.js

If you ended a timer without first starting it, it would throw an error.
While testing the redirectAllowList, I found that if you throw an error within [createRequestHtmlFragment](https://github.com/americanexpress/one-app/blob/5.x.x/src/server/middleware/createRequestHtmlFragment.jsx) before starting serverPhaseTimer 7, the error would get caught and attempt to end timer 7. This would end up throwing an error outside of a try/catch and crash the server
Tested with the same method used to find this error, throwing an error in the redirect flow an ensuring the server didn't crash.
Also unit tested

fix(tracer): ending timers without starting would crash server

---

Dockerfile
__tests__/server/utils/__snapshots__/renderModuleStyles.spec.js.snap
__tests__/server/utils/renderModuleStyles.spec.js
src/server/utils/renderModuleStyles.js

This PR:
- fixes a cascade ordering issue between server and client bundles, leading to style inconsistencies when hydrated.
- enables deduplication between modules for identical styles, i.e. if a component library imports styles via css modules.
- provides the ability for SSR generated styles to directly match the expected output of CSR styles, preventing a flash of restyling as the browser processes the Recalculate Styles task.
When using a component library (or any dependency) that imports styles via CSS Modules, the bundler output generates a server bundle that is inconsistent with the client side bundle, as well as resulting in it being difficult to provide style overrides without resorting to CSS hacks (like !important).
In order to resolve this and match the client side bundle …

feat(styleLoader): aggregate stylesheets and dedupe if already loaded

---

.gitignore
__tests__/integration/one-app.spec.js
package-lock.json
package.json
prod-sample/sample-modules/cultured-frankie/0.0.0/package.json
prod-sample/sample-modules/cultured-frankie/0.0.1/package.json
prod-sample/sample-modules/frank-lloyd-root/0.0.0/package.json
prod-sample/sample-modules/frank-lloyd-root/0.0.1/package.json
prod-sample/sample-modules/frank-lloyd-root/0.0.2/package.json
prod-sample/sample-modules/frank-lloyd-root/0.0.3/package.json
prod-sample/sample-modules/frank-the-parrot/0.0.0/package.json
prod-sample/sample-modules/franks-burgers/0.0.0/package.json
prod-sample/sample-modules/healthy-frank/0.0.0/package.json
prod-sample/sample-modules/late-frank/0.0.0/package.json
prod-sample/sample-modules/late-frank/0.0.1/package.json
prod-sample/sample-modules/late-frank/0.0.2/package.json
prod-sample/sample-modules/needy-frank/0.0.0/package.json
prod-sample/sample-modules/needy-frank/0.0.1/package.json
prod-sample/sample-modules/picky-frank/0.0.0/package.json
prod-sample/sample-modules/picky-frank/0.0.1/package.json
prod-sample/sample-modules/preview-frank/0.0.0/package.json
prod-sample/sample-modules/ssr-frank/0.0.0/package.json
prod-sample/sample-modules/unhealthy-frank/0.0.0/package.json
prod-sample/sample-modules/vitruvius-franklin/0.0.0/package.json
prod-sample/sample-modules/vitruvius-franklin/0.0.1/package.json

backport for - https://github.com/americanexpress/one-app/pull/1132

chore(sample-modules): support node 18 (#1132)

---

__tests__/server/middleware/pwa/offline.spec.jsx
package-lock.json
package.json

Update to latest holocron version.
Update to latest holocron that has additional console warnings and need installed into the app to be available to the modules.
Allows modules to access this version via the bundler.
npm packed the library and installed it into the app to see it working.
Will see more warnings in console and on logging services when modules fail during load server side. The warnings represent existing issues.

chore(package): bump holocron to 1.8.1

---

__tests__/server/utils/cdnCache.spec.js
src/server/utils/cdnCache.js

Fix initialization of cache object and stringify.
`JSON.stringify('{}')` to `JSON.stringify({})`
It caused caching issue, as it was trying to key value in string instead of object.

fix(cache-cdn): stringify object

---

.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml
.github/workflows/release-step-2_automatic_tag-release.yml
.github/workflows/release-step-3_automatic_prepare-docker-tags.yml
.github/workflows/release-step-4_automatic_docker-prod-build-and-publish.yml
.github/workflows/release-step-5_automatic_docker-dev-build-and-publish.yml
.github/workflows/release-step-6-automatic_publish-one-app-statics-to-npm.yml

replace
```shell
echo "::set-output name={name}::{value}"
```
with
```shell
echo "{name}={value}" >> $GITHUB_OUTPUT
```
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
these are now showing as warnings in the runs, e.g. https://github.com/americanexpress/one-app/actions/runs/6344142425
I guess we'll see a run of [.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml](https://github.com/americanexpress/one-app/pull/1141/files#diff-3d711afca65f83d28d66cf77532c7acac0f14c39b4aa56d650686873a35065f6) on this PR 🤞 
None

chore(workflows): use GITHUB_OUTPUT instead of ::set-output

---

__tests__/server/plugins/reactHtml/index.spec.jsx
package-lock.json
package.json
src/server/plugins/reactHtml/index.jsx

Fallback externals do not support legacy, remove legacy logic to ensure does not load missing scripts.
Don't attempt to include integrity when missing, this is requires as fallback externals do not include integrity values
Fix SSR when fallback externals are required and has no integrity value provided
Test suite

fix(reactHtml): renderScripts adding unknown integrity

---

package.json

Our engines field doesn't accurately represent the Node versions we support. 
This fixes that by making it obvious that we only support 16 -> 18

chore(package): set engines to accurately represent node support

---

__tests__/server/config/env/runTime.spec.js
src/server/config/env/runTime.js

Changes the default development ONE_CLIENT_REPORTING_URL and ONE_CLIENT_CSP_REPORTING_URL to use relative URLs instead of URLs with a hostname.
Fixes #1193 by not using the internal docker IP address.
Ran locally with one-app-runner using these updated variables and verified that report endpoints responded with 204 and printed reports to console.
When running in Docker, Javascript errors should be printed to the console rather than not being reported.

fix(runTime): use relative urls for defaulted report variables

---

__tests__/server/utils/logging/config/otel.spec.js
src/server/utils/logging/config/otel.js

Give the OTel pino transport an object instead of an array with a single entry when in production
Relates to Vunovati/pino-opentelemetry-transport#106
Currently startup in production results in a log to STDOUT that is not useful
```
MultiLogRecordProcessor [
<ref *1> BatchLogRecordProcessor {
_exporter: OTLPLogExporter {
_sendingPromises: [],
url: '0.0.0.0:4317',
shutdown: [Function: bound shutdown],
_shutdownOnce: [BindOnceFuture],
_concurrencyLimit: Infinity,
timeoutMillis: 10000,
grpcQueue: [],
serviceClient: undefined,
metadata: [Metadata],
compression: 0
},
_finishedLogRecords: [],
_maxExportBatchSize: 512,
_maxQueueSize: 2048,
_scheduledDelayMillis: 5000,
_exportTimeoutMillis: 30000,
_shutdownOnce: BindOnceFuture {
_callback: [AsyncFunction: _shutdown],
_that: [Circular *1], …
```

refactor(otel): remove unnecessary log on startup in prod

---

package-lock.json
package.json

update env-config-utils
Adopt this fix americanexpress/env-config-utils#46
which is causing an erroneous log when OTel logging is not enabled
started the application before and after the change both with and without OTel enabled
- before with: logs erroneous message
- before without: logs message correctly
- after with: logs message clorrectly
- after without: does not log erroneous message
Eliminate erroneous message when not using OTel logging

chore(deps): update env-config-utils for fix

---

__tests__/server/ssrServer.spec.js
src/server/ssrServer.js

Set HTTP status code to 500 in application error handler
Application errors were causing HTTP 200 responses
Triggered an application error caused by bug fixed in #1242 validated that HTTP status of error page was 200 before change and 500 after
> Note: integration tests will fail until #1242 is merged
Correct HTTP status of application errors

fix(errorHandler): application errors would result in a 200 response

---

__tests__/server/utils/cdnCache.spec.js
src/server/utils/cdnCache.js

Changes the message from:
```
LOG: **************************************************************
LOG: CACHE INFORMATION
LOG: File size of .one-app-module-cache: 1.00 MB
LOG: To delete cache, please run
LOG:     rm  /home/node/.one-app/.one-app-module-cache
LOG: **************************************************************
```
to:
```
LOG: **************************************************************
LOG: CACHE INFORMATION
LOG: File size of .one-app-module-cache: 1.00 MB
LOG: To clear the cache, please delete this file:
LOG:     ~/.one-app/.one-app-module-cache
LOG: **************************************************************
```
This is trying to be generic enough to work across Mac and Windows and standalone and Docker, but it's a difficult problem.
Fixes #1244 
Namely, running `rm …

fix(cdnCache): make clear cache message generic

---

.github/labeler.yml
.github/workflows/on-pr_pr-labeler.yml

there was a change in syntax from pr labeler v4 to 5 this updates it to fix it
https://github.com/americanexpress/one-app/pull/1253 tested with this pr

fix(actions): update pr labeler syntax

---

README.md

fix(badges): fix readme badges

---

.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml
docs/guides/Publishing-Modules.md
docs/guides/Running-One-App-Locally.md
package-lock.json
package.json

- Don't run tests on Node 16 or allow building on Node 16
- Run unit/lint tests on Node 20
Node 16 has been EOL for quite some time now and we upgrade our image to Node 18 ages ago
The unit tests already pass on Node 20, so adding it to prevent regressions on that before we upgrade
`npm run build` (only the build script was affected)
N/A

chore(node): drop node 16

---

.github/labeler.yml
.github/workflows/on-pr_pr-labeler.yml
README.md

Updated PR labeler config to accommodate breaking changes
This workflow is currently failing
See successfully labeled PR #1286 
N/A

chore(workflows): fix labeler action config

---

.github/labeler.yml

Update labeler config glob from `*/**` to `**`
Current config excludes files in the root directory
See successful run in #1288 
N/A

chore(workflows): labeler config did not match files at root

---

__tests__/server/utils/devCdnFactory.spec.js
package-lock.json
package.json
src/server/utils/devCdnFactory.js

fix to the dev cdn which would leave the requested url with two // in front of the incomingRequestPath
tested with unit tests

fix(devCdn): removing extra / which created malformed url

---

__tests__/server/utils/__snapshots__/renderModuleStyles.spec.js.snap
__tests__/server/utils/renderModuleStyles.spec.js
src/server/utils/renderModuleStyles.js

This change ports #1099 from one-app@6 to one-app@5. 
This change is raised to support an existing one-app@6 feature in one-app@5. For the original motivation and context, please see the original PR (#1099). 
To test this change, I generated a root module and two child modules which all render on a single page. Within each module, I have installed a basic component library that imports a css module within the component:
```jsx
// Button.jsx
import styles from './styles.module.css';
// ...
<button {...otherProps} className={clsx(styles.button, className)}>
{children}
</button>
```
```css
/* styles.module.css */
.button {
background-color: blue;
color: white;
border: none;
padding: 8px 16px;
}
```
Within each module, I've also created a `styles.module.css` with a class that changes the …

feat(styles-loader): aggregate stylesheets and dedupe if already loaded

---

.github/workflows/on-pr_one-app-integration-tests.yml
__tests__/integration/__snapshots__/one-app.spec.js.snap
__tests__/integration/helpers/testRunner.js
__tests__/integration/one-app.spec.js
prod-sample/docker-compose.yml
prod-sample/otel-collector/config.yaml
scripts/build-one-app-docker-setup.js

Use file exporter for logs in otel collector during integration tests & upload logs and traces as artifacts
Better debuggability of integration tests on GH
This PR
N/A

test(integration): use otel file exporter instead of logging exporter

---

.gitignore
docs/api/server/Environment-Variables.md
package-lock.json
package.json
scripts/start.sh

Add [Dotenv](https://github.com/motdotla/dotenv) support
Allow users to define environment variables with a file on startup.
Drafted a pre-release and tested in an environment
https://hub.docker.com/layers/oneamex/one-app/6.11.0-dotenvsupport.0/images/sha256-d81828183b68f026e2a69f6be70046f33bbb2045b2b8ca3638dd45a9be485d9e?context=explore
Also ran the image locally to ensure modules can supply their own file locally.
**NOTE**
one-app-runner currently has a bug where it will ignore the startup command defined in the Dockerfile, and start the process with its own command. We will need to resolve this, but it breaks nothing currently. 
New feature!

feat: add dotenv support

---

package-lock.json
package.json

Update to `conventional-changelog-cli@4.1.0`
This was incorrectly flagged as not upgradable in #1327 due to the conflicting version that `standard-version` relies on. Seems upgrading `@commitlint/cli` and `@commitlint/config-conventional` without updating `conventional-changelog-cli` may have been the cause of this issue.
Release PRs are generating bad changelogs
Ran `$ npm run release`
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 9391174..1282f8a 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -2,6 +2,9 @@
All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.
+
+
+
```
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 9391174..f2432d8 100644
--- …
```

Fix release workflow

---

.dockerignore

Ignore the build cache and stats when building the image.
The build ~~cache~~ [stats] can grow to hundreds of MBs. Ignoring it reduces the context transfer by two orders of magnitude, which is also a speedup of building the image.
Found this as the culprit using [dive](https://github.com/wagoodman/dive#readme).
Ran `$ docker run .` locally
Less time waiting if building the image locally.

chore(docker): ignore build cache

---

package-lock.json
package.json

Update  @americanexpress/one-app-server-bundler to 1.0.3
See americanexpress/one-app-cli#629
Validated manually by @code-forger
Will be able to serve modules without legacy bundle

fix(serve-module): dev cdn would fail to start when serving modules without a legacy bundle

---

__tests__/integration/one-app.spec.js
__tests__/server/utils/tracer.spec.js
package-lock.json
package.json
prod-sample/api/server.js
prod-sample/sample-modules/ssr-frank/0.0.0/src/components/SsrFrank.jsx
src/server/utils/tracer.js

Add B3 propagator to tracer
Support systems that do not support W3 trace context for propagation
Ran locally connecting to said system, saw traces reflected in jaeger

feat(tracing): include B3 propagator

---

__tests__/integration/helpers/testRunner.js

Only send logs from integration tests to stdout on runner debug
https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
When tests are passing, this is just noise. Logs are available as file artifact either way
This PR. 
- [attempt #1](https://github.com/americanexpress/one-app/actions/runs/8512209359/job/23313361372?pr=1351) no logs in stdout
- [attempt #2](https://github.com/americanexpress/one-app/actions/runs/8512209359/job/23313793977?pr=1351) with debug checkbox checked, logs in stdout
N/A

test(integration): only send logs to stdout on debug runs

---

.github/pr-labeler.yml
.github/workflows/bundle-size.yml
.github/workflows/on-pr-and-trunk_one-app-unit-and-lint-tests.yml
.github/workflows/on-pr_dangerJS.yml
.github/workflows/on-pr_one-app-integration-tests.yml
.github/workflows/release-step-1_manual_create-release-pr.yml
package.json

> Note: **Build Size - gzipped / build (pull_request)** is _expected_ to fail for this PR because the script does not exist in main
Remove `postinstall` and `preinstall` scripts
Also fixed an issue with the bundle-size workflow which was validating development asset size instead of production asset size. I had to add a new script for it since you can't define NODE_ENV separately for install and build scripts in this workflow.
Minor refactor in how NODE_ENV is set in workflows.
`presinstall` runs `check-engines` which is not needed since we have `engine-strict=true` in `.npmrc`. That enforces this without an additional dependency.
`postinstall` runs `npm run build` which is not super useful as we don't always need a build on every install, and often we need a production build, so we have …

chore(scripts): remove postinstall and preinstall

---

__tests__/server/utils/watchLocalModules.spec.js
src/server/utils/watchLocalModules.js

This fixes users seeing the following log when re-building locally served modules running the dev server:
```Encountered error fetching module at undefinedmodule-config.json: Only absolute URLs are supported```
This bug means the module-config.json will never load, and the users sees an error they have no way of understanding
running agains reproduction case
unit tests
No more confusing log

fix(watchLocalModules): fix missing baseUrl
