- README.md
- Added API Docs section
- Built out Module hierarchy in API docs section
- Added `appConfig` API docs
> docs(api): module app config in readme

- docs/api/API.md
- docs/api/server/CLI-Commands.md
- docs/api/server/Development-Tools.md
- docs/api/server/Environment-Variables.md
- docs/api/server/Module-Map.md
- CLI Commands API Doc
- Stubbed out other Server API Doc files
> Part 1 of Server API Docs: docs(server): cli commands docs

- docs/api/modules/State-Management.md
Cleared up a few points to make docs friendlier to new users
> docs(state-management): clear up

- package-lock.json
- package.json
See https://github.com/americanexpress/one-app-dev-cdn/pull/4
> fix(devCdn): proxy modules through dev cdn

- package-lock.json
- package.json
This updates `one-app` to the latest `@americanexpress/one-app-dev-cdn`
Update to the latest version so running with docker points to localhost instead of docker IP address.
Manually running One App with modules and verifying everything still works.
> chore(deps): update one-app-dev-cdn

- package-lock.json
- package.json
- prod-sample/sample-modules/cultured-frankie/0.0.0/package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.1/package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.2/package-lock.json
- prod-sample/sample-modules/healthy-frank/0.0.0/package-lock.json
Updates `acorn` to `v7.1.1`
https://snyk.io/vuln/SNYK-JS-ACORN-559469
> chore(deps): upgrade acorn to 7.1.1

- .github/workflows/stale.yml
Update stale PR to not mark enhancements as stale and closed.
Enhancement issues were being closed when they shouldn't
N/A since it is a GitHub action
> chore(workflow): update stale workflow

- .dockerignore
Adding entries to dockerignore that are not adding value by being in the docker image. Makes for a (slightly) smaller image!
Adding entries to dockerignore that are not adding value by being in the docker image. Makes for a (slightly) smaller image!
See above...
Built image and made sure those files are no longer being bundled.
Slightly faster docker pull for the one app images!
> chore(dockerignore): add files not needed in docker image

- CHANGELOG.md
- one-app-statics/package.json
- package-lock.json
- package.json
One App prerelease v5.0.0-rc.0
One App prerelease for v5.0.0-rc.0
Running unit tests and integrations tests
This would release v5.0.0-rc.0 to be used by One App developer to build experiences
> chore(release): 5.0.0-rc.0

- docs/recipes/Internationalizing-Your-Module.md
Documentation covers locale file structure, setting up an intl provider, and accessing intl package in child components. Fixes https://github.com/americanexpress/one-app/issues/60
Provide a quick way to start internationalizing a One App module.
N\A - Documentation only.
No impact to existing developers. Happier future developers.
> docs(recipes): update internationalization

- CHANGELOG.md
- one-app-statics/package.json
- package-lock.json
- package.json
Releasing version `5.0.0-rc.1`
> chore(release): 5.0.0-rc.1

- CONTRIBUTING.md
- __tests__/server/middleware/createRequestStore.spec.js
- __tests__/server/utils/logging/development-formatters/__snapshots__/friendly.spec.js.snap
- __tests__/server/utils/logging/development-formatters/friendly.spec.js
- __tests__/server/utils/safeRequest.spec.js
Fix grammatical errors across project. Fixes Issue #117 
Helps improve the documentation and readability. 
Ran locally after making the changes. 
It just helps improve code readability and quality.
> chores : fix typos in docs

- docs/api/modules/App-Configuration.md
- docs/api/modules/Loading-Data.md
- docs/api/modules/Loading-Modules.md
- docs/api/modules/Routing.md
- docs/api/modules/State-Management.md
**Non breaking change**
Update docs with Templating changes to support One Docs
Add Merge Tags for our upcoming documentation site.
None from One App's perspective.
> One doc templating

- CHANGELOG.md
- one-app-statics/package.json
- package-lock.json
- package.json
> chore(release): 5.0.0-rc.2

- __tests__/client/__snapshots__/initClient.spec.js.snap
- src/client/initClient.jsx
Removed `<StrictMode />` from always being wrapped around the app, allowing users to opt in by including it in their modules.
Resolves #74 
I ran the app locally to see that there were no more strict mode related errors in the console with the prod-sample modules
There will no longer be errors by default and strict mode will be opt-in only
> feat(initClient): removed StrictMode, resolves #74

- docs/api/modules/App-Configuration.md
Fixing documentation template comments inside App Configuration
N/A
> docs(api): fixes to templating in app config

- CHANGELOG.md
- one-app-statics/package.json
- package-lock.json
- package.json
> Prepare release

- package-lock.json
- package.json
Updating `@americanexpress/one-app-ducks` to v`4.0.1` to fix additional slash to language pack urls.
With One App testing (unit + integration)
Fixes the language pack url for `intl`.
> chore(deps): update one-app-ducks

- docs/api/modules/App-Configuration.md
Removes `appCompatibility` from the docs as it does not belong within appConfig, it should be in the bundler.
So that end users are not confused on where to add app compatibility.
N/A
> docs(appconfig): update app config docs

- CHANGELOG.md
- one-app-statics/package.json
- package-lock.json
- package.json
> Prepare release 5.0.0-rc.5

- package-lock.json
- package.json
Remove unused dependency tough-cookie
dependency is unused
One App test suite
None
> chore(tough-cookie): remove

- package-lock.json
Ran `npm audit fix` and resulted in 8 low deps remaining.
Less at risk dependencies for cloners and prod builds
> chore(deps): audit fix deps

- .travis.yml
Only test unit & integration once per nodejs version (12.x, 14.x).
Faster PR experience with `one-app`
> chore(travis): run only two jobs

- docs/recipes/README.md
Removing pin for code split docs that already exist.
Docs communication when reading `docs/recipes/README.md`.
> docs(recipes): remove tack from code split in readme

- __tests__/server/config/env/argv.spec.js
during the argv.spec.js beforeAll if locally served modules the `static/module-map` was being cached by the `require` resulting in failing specs .
Improve DX and ensure tests pass during local development.
Running the unit test with locally served modules/
N/A
> test(argv): dont cache static/module-map during setup

- src/server/utils/clientModuleMapCache.js
Ensure base url is correct for each module bundle.
> fix(clientModuleMapCache): set base url for module bundle type

- .travis.yml
Currently running full test suite on before node 12 and 14. This is probably overkill and slows us down.
Increase potential pr speed
Using this PR to test
None
> chore(travis): only run full test suite on node 12

- package.json
This add `cross-env` to the `build:server` script so that it does not fail on a Windows machine
So that building One App does not fail on a Windows machine
Tested on a Windows machine where the build was failing due to this.
N/A
> chore(script): add cross-env to build:server

- __tests__/server/utils/createCircuitBreaker.spec.js
- package-lock.json
- package.json
- src/server/utils/createCircuitBreaker.js
Log circuit breaker opens, closes and healthcheck failures
Provides better insight and monitoring
Included unit tests
Developers will see circuit breaker activities in their logs
> feat(createCircuitBreaker): log circuit breaker activity

- docs/api/README.md
- docs/api/modules/App-Configuration.md
- docs/api/modules/Internationalization.md
- docs/api/modules/Loading-Data.md
- docs/api/modules/Loading-Modules.md
- docs/api/modules/Routing.md
- docs/api/modules/State-Management.md
- docs/recipes/Adding-Styles.md
- docs/recipes/Code-Splitting-Using-Holocron.md
- docs/recipes/Deploying-Modules.md
- docs/recipes/Enabling-Serverside-Rendering.md
- docs/recipes/Internationalizing-Your-Module.md
- docs/recipes/Making-An-Api-Call.md
- docs/recipes/Mocking-Api-Calls.md
- docs/recipes/Monitoring-One-App.md
- docs/recipes/Partial-Rendering.md
- docs/recipes/README.md
- docs/recipes/Routing-And-Navigation.md
- docs/recipes/Running-Existing-App-Locally.md
- docs/recipes/Running-In-Production.md
Hide the "return to readme" links at the top of the documentation files in https://one-amex-docs.americanexpress.com/
> docs(links): hide return to links

- __tests__/server/middleware/pwa/config.spec.js
Adds unit test for PWA where there is no config passed.
To add a unit test to cover a previous fix.
N/A
> test(pwa): add a test for no config

- Dockerfile
fix for dockerfile. user was being set before `chown` was run. This caused permissions issues as node does not have permission to run `chown`
built docker prod image locally.
> fix(dockerfile): set user after chown

- __tests__/integration/one-app.spec.js
- prod-sample/sample-modules/franks-burgers/0.0.0/locale/en-US.json
- prod-sample/sample-modules/franks-burgers/0.0.0/package-lock.json
- prod-sample/sample-modules/franks-burgers/0.0.0/package.json
- prod-sample/sample-modules/franks-burgers/0.0.0/src/components/Burger.jsx
- prod-sample/sample-modules/franks-burgers/0.0.0/src/components/index.jsx
Simplify integration module `franks-burgers` for testing.
> fix(integration-tests): simplify franks burgers

- .github/workflows/integrations_test.yml
- .github/workflows/pull_request_release.yml
- .github/workflows/release_drafter.yml
- .github/workflows/tagging.yml
- CONTRIBUTING.md
- README.md
- RELEASE.md
- docs/api/modules/App-Configuration.md
- docs/api/modules/Internationalization.md
- docs/api/modules/Loading-Data.md
- docs/api/modules/Loading-Modules.md
- docs/api/modules/Routing.md
- docs/api/modules/State-Management.md
- docs/api/server/Cli-Commands.md
- docs/api/server/Module-Map-Schema.md
- docs/recipes/Adding-Styles.md
- docs/recipes/Code-Splitting-Using-Holocron.md
- docs/recipes/Internationalizing-Your-Module.md
- docs/recipes/Mocking-Api-Calls.md
- docs/recipes/Publishing-Modules.md
- docs/recipes/Running-In-Production.md
- one-app-statics/README.md
- package.json
Switching over to use `main` as the default branch
> chore(main): switch over to main

- package-lock.json
- package.json
- prod-sample/README.md
- scripts/build-sample-modules.js
- scripts/deploy-prod-sample-module.js
- scripts/utils.js
> Update main with master

- __tests__/server/middleware/__snapshots__/csp.spec.js.snap
- src/server/middleware/csp.js
Loosen development CSP to allow all ports on localhost and the machines ip
Limiting script src and connect src to one-app specific ports was too limiting for quick local development
Locally and test suite.
> feat(csp): loosen development to use localhost or ip '*'

- package-lock.json
- prod-sample/sample-modules/cultured-frankie/0.0.0/package-lock.json
- prod-sample/sample-modules/cultured-frankie/0.0.1/package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.0/package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.1/package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.2/package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.3/package-lock.json
- prod-sample/sample-modules/frank-the-parrot/0.0.0/package-lock.json
- prod-sample/sample-modules/franks-burgers/0.0.0/package-lock.json
- prod-sample/sample-modules/healthy-frank/0.0.0/package-lock.json
- prod-sample/sample-modules/late-frank/0.0.0/package-lock.json
- prod-sample/sample-modules/late-frank/0.0.1/package-lock.json
- prod-sample/sample-modules/late-frank/0.0.2/package-lock.json
- prod-sample/sample-modules/needy-frank/0.0.0/package-lock.json
- prod-sample/sample-modules/needy-frank/0.0.1/package-lock.json
- prod-sample/sample-modules/picky-frank/0.0.0/package-lock.json
- prod-sample/sample-modules/picky-frank/0.0.1/package-lock.json
- prod-sample/sample-modules/preview-frank/0.0.0/package-lock.json
- prod-sample/sample-modules/ssr-frank/0.0.0/package-lock.json
- prod-sample/sample-modules/vitruvius-franklin/0.0.0/package-lock.json
- prod-sample/sample-modules/vitruvius-franklin/0.0.1/package-lock.json
Updates to 1.5.1 of webpack-subresource-integrity
Update it to fix a security vulnerability
> chore(deps): bump webpack-subresource-integrity to 1.5.1

- .github/pull_request_template.md
> chore(template): update PR template

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
Configures code scanning https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning
> chore(codeql): add codeql analysis workflow

- package-lock.json
- package.json
Updates `conventional-changelog-cli
Opening due to #364 having too long of a commit body.
> chore(deps): update conventional-changelog-cli to 2.1.1

- __performance__/README.md
- docs/recipes/Monitoring-One-App.md
- docs/recipes/README.md
Basic info on metrics and monitoring.
> docs(recipes): monitoring one app

- docs/recipes/Enabling-Serverside-Rendering.md
Update import statement
So that the documentation is correct
N/A
N/A Just a docs update
> docs(ssr): update import statement

- .github/workflows/integrations_test.yml
- package-lock.json
- package.json
Remove surge from the dependency list since is not needed.
- During integration tests we are using `npx surge` so the surge dependency is not required by one-app.
- By removing `surge` as a dependency we also remove the dependency on `tarr` a package created by the surge-cli developers and not the officially supported `tar`
- Add missing env Var `'${{ secrets.HEROKU_APP_URL }}'` to the `CORS` configuration section instead of the hardcoded domain.
Removes unnecessary dependency
Successful integration test run using the new configuration: 
https://github.com/infoxicator/one-app/runs/1353253663?check_suite_focus=true
> test(integration): remove surge dependency

- docs/recipes/Enabling-Serverside-Rendering.md
> docs(ssr): add missing word

- .github/workflows/tagging.yml
Release process is currently failing due to github actions deprecating `::set-env`
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> fix(tagging/workflow): use ::set-output over ::set-env

- docs/overview/README.md
> docs(overview): fix image links

- docs/recipes/Module-Composition.md
Make docs a little more clear by adding `import` statements above the code
> docs(recipes): add import statements to module composition

- .github/workflows/dangerJS.yml
- .github/workflows/integrations_test.yml
- .github/workflows/pull_request_integration_test .yml
- .github/workflows/pull_request_release.yml
- .github/workflows/unit_test.yml
Updated `actions/cache@v1` to `actions/cache@v2` and `peter-evans/create-pull-request@v2` to `peter-evans/create-pull-request@v3` which were causing the action to fail.
https://github.com/nellyk/one-app/actions/runs/483432994
> chore(workflow): update workflow actions versions

- docs/recipes/README.md
> docs(recipes): add missing link to one app runner

- src/server/middleware/createRequestHtmlFragment.jsx
Uses `util.format()`
https://github.com/americanexpress/one-app/security/code-scanning/3?query=ref%3Arefs%2Fheads%2Fmain
Unit tests still pass
> fix(middleware): use util.format in createRequestHtmlFragment

- .github/workflows/issue-triage.yml
- CONTRIBUTING.md
- README.md
Replaces slack link with GitHub discussions link.
Use GitHub discussions over Slack.
> docs(community): replace slack with GitHub discussions link

- docs/overview/Configuration.md
- docs/overview/Getting-Started.md
- docs/overview/Lifecycle.md
There were broken links when using the overview documentation.
Corrected the URLs to broken links found in the overview docs, many were missing the `.md` extension and failed to link to documentation on GitHub.
> docs(overview): fix broken links

- package-lock.json
- package.json
Updates `one-app-ducks` to the latest version.
Keeps the dependency up to date and fixes the bug in `one-app-ducks`.
> fix(deps): bump one-app-ducks to 4.3.1

- prod-sample/sample-modules/frank-lloyd-root/0.0.2/package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.2/package.json
- prod-sample/sample-modules/late-frank/0.0.1/package-lock.json
- prod-sample/sample-modules/late-frank/0.0.1/package.json
Updated prod sample repos used during integration tests to use the latest version of the bundler that fixes a bug where externals are overwritten by a non-root module providing externals incorrectly.
Our integration tests didn't catch this bug previously because, the test included the same external library `@emotion/core` provided correctly by `frank-lloyd-root` but incorrectly by `late-frank`. `late-frank` was overriding the externals array but because it was the same as provided by the root module the test passed.
This PR provides a different external and correctly ensures that the ones provided by the root module are not overwritten by a child module.
context https://github.com/americanexpress/one-app-cli/pull/216
> test(integration): update bundler and verify externals override

- __performance__/docker-compose.yml
Influx DB v2 release contained breaking changes and will require some additional work to make our current perf dockerfile compatible
> chore(performance/influxdb): set version 1.8

- .github/dependabot.yml
- .github/workflows/automated-pr.yml
- .github/workflows/automerge-dependabot.yml
Automerge of dependabot PRs to branch dependabot-changes
Adding automated PR that is raised every Monday with changes
Automate tasks and reduce the number of PRs we have to review and still ensure the project is upto date with security updates
- auto merging minor and patches after they pass tests e.g nellyk/task-list-pr-checker#59 this is workflow https://github.com/nellyk/task-list-pr-checker/blob/main/.github/workflows/automerge.yml
- Automated PR is then raised with all the changes nellyk/task-list-pr-checker#63 and nellyk/redux-exercise-notes#30
Enable faster update of dependencies
> Automerge dependabot PRs

- docs/api/README.md
remove a link to [docs/api/server/Development-Tools.md](https://github.com/americanexpress/one-app/blob/bf881a40929bbdc23017da9cf18807628c20d093/docs/api/server/Development-Tools.md) which was [removed in #105](https://github.com/americanexpress/one-app/pull/105/files#diff-69f9c705a466a8b140776dda20c4231e1eb2deffb8dd5c121e16d86c134263e9)
this resolves a 404 when following the link
n/a
n/a
> docs(api): remove link to removed resource

- .github/workflows/tagging.yml
only get the subject line from commit message. This should account for scenarios when body includes additional information. 
To make release commit message more flexible.
Locally tested that this would return expected commit message format
> chore(workflow): only get subject of commit message

- .github/workflows/unit_test.yml
- __tests__/server/middleware/__snapshots__/createRequestHtmlFragment.spec.js.snap
- __tests__/server/middleware/createRequestHtmlFragment.spec.js
- package-lock.json
- package.json
- prod-sample/sample-modules/cultured-frankie/0.0.0/package.json
- prod-sample/sample-modules/cultured-frankie/0.0.1/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.0/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.1/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.2/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.3/package.json
- prod-sample/sample-modules/frank-the-parrot/0.0.0/package.json
- prod-sample/sample-modules/franks-burgers/0.0.0/package.json
- prod-sample/sample-modules/healthy-frank/0.0.0/package.json
- prod-sample/sample-modules/late-frank/0.0.0/package.json
- prod-sample/sample-modules/late-frank/0.0.1/package.json
- prod-sample/sample-modules/late-frank/0.0.2/package.json
- prod-sample/sample-modules/needy-frank/0.0.0/package.json
- prod-sample/sample-modules/needy-frank/0.0.1/package.json
- prod-sample/sample-modules/picky-frank/0.0.0/package.json
- prod-sample/sample-modules/picky-frank/0.0.1/package.json
- prod-sample/sample-modules/preview-frank/0.0.0/package.json
- prod-sample/sample-modules/ssr-frank/0.0.0/package.json
- prod-sample/sample-modules/vitruvius-franklin/0.0.0/package.json
- prod-sample/sample-modules/vitruvius-franklin/0.0.1/package.json
- scripts/build-one-app-docker-setup.js
- src/server/utils/heapdump.js
This includes the changes in #611, adding the support without changing the image and integration tests.
Prep for v6
`npm test`
> feat(runtime): support node 16

- prod-sample/sample-modules/frank-lloyd-root/0.0.0/src/config.js
- prod-sample/sample-modules/frank-lloyd-root/0.0.2/src/config.js
- prod-sample/sample-modules/frank-lloyd-root/0.0.3/src/config.js
FIxing #445 
example code had dangerous object references
Provide better examples
N/A
> fix(prodsample): configureRequestLog had faulty example code

- package-lock.json
- package.json
Bump holocron to v1.2.1
This fixes an issue with holocron v1.2.0
> chore(dep): bump holocron to v1.2.1

- .github/labeler.yml
- .github/workflows/pr_labeler.yml
'These are the same approved changes from https://github.com/americanexpress/eslint-config-amex/pull/99 '
Updating git hub actions pertaining to labeling for one-app team
-> update to repo config
> chore(labeler): adding updated workflows

- package-lock.json
- package.json
update one-app-ducks
includes fix for in one-app-ducks which correctly removes errors on successful retry of lang pack request
> fix(one-app-ducks): delete lang pack request errors

- CHANGELOG.md
- one-app-statics/package.json
- package-lock.json
- package.json
> chore(release): 5.13.3

- __tests__/server/config/env/__snapshots__/runTime.spec.js.snap
- __tests__/server/config/env/runTime.spec.js
- __tests__/server/ssrServer.spec.js
- docs/api/server/Environment-Variables.md
- package-lock.json
- package.json
- src/server/config/env/runTime.js
- src/server/ssrServer.js
The max POST payload size was hardcoded to 15kb. This PR makes that setting configurable. It also fixes an issue where the env var to enable POSTing would enable the feature when set to any value at all, including "false"
The use case for this change is a performance enhancement for modules that had to make a GET request during SSR for data that could have been included in the POST, but exceeded the limit.
Unit tests only
> feat(ssrServer): make max POST request payload size configurable

- .github/workflows/release-step-5_automatic_docker-dev-build-and-publish.yml
> chore(workflows): docker-dev-build fix tag

- package-lock.json
> chore(browserslist): npx browserslist@latest --update-db

- RELEASE.md
updated release.md
provide more details on release.
> docs(release): update for new workflows

- .github/workflows/release-step-4_automatic_docker-prod-build-and-publish.yml
> chore(workflow): fix typo in client_payload in Release 4

- Dockerfile
pined versions instead of using major only
To specify the exact versions on dockfile
NA
NA
> feat(update): updated node and npm versions on docker file

- package-lock.json
- package.json
Updated @americanexpress/fetch-enhancers to 1.1.2 which now creates a esm build that can be more efficiently tree shaken. 
reduce app.js bundle size
bundling and analyzing build locally
before:
after:
> fix(fetch-enhancers): use tree-shakable es build

- __tests__/server/middleware/sendHtml.spec.js
- src/server/middleware/sendHtml.js
Respect `disableStyles` to remove ssr-css for partial routes
While disableStyles set via `setDangerouslyDisableScriptsAndStyles` when set for normal routes removes the ssr-css, but the disableStyles value is not respected in case of partial routes (set via `renderPartialOnly`/`setRenderPartialOnly` action)
Unit test added
> fix(renderPartial): respect disabledStyles for partial render

- __tests__/server/metrics/__snapshots__/intl-cache.spec.js.snap
- __tests__/server/metrics/intl-cache.spec.js
- __tests__/server/metricsServer.spec.js
- package-lock.json
- package.json
- src/server/metrics/intl-cache.js
- src/server/metricsServer.js
updated prom-client and  made alterations to handle with breaking changes. 
prom-client@12 was using deprecated node performance apis. this gets around that.
locally by comparing metrics before and after.
> chore(metrics-server): update prom-client

- prod-sample/sample-modules/cultured-frankie/0.0.0/package.json
- prod-sample/sample-modules/cultured-frankie/0.0.1/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.0/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.1/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.2/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.3/package.json
- prod-sample/sample-modules/frank-the-parrot/0.0.0/package.json
- prod-sample/sample-modules/franks-burgers/0.0.0/package.json
- prod-sample/sample-modules/healthy-frank/0.0.0/package.json
- prod-sample/sample-modules/late-frank/0.0.0/package.json
- prod-sample/sample-modules/late-frank/0.0.1/package.json
- prod-sample/sample-modules/late-frank/0.0.2/package.json
- prod-sample/sample-modules/needy-frank/0.0.0/package.json
- prod-sample/sample-modules/needy-frank/0.0.1/package.json
- prod-sample/sample-modules/picky-frank/0.0.0/package.json
- prod-sample/sample-modules/picky-frank/0.0.1/package.json
- prod-sample/sample-modules/preview-frank/0.0.0/package.json
- prod-sample/sample-modules/ssr-frank/0.0.0/package.json
- prod-sample/sample-modules/unhealthy-frank/0.0.0/package.json
- prod-sample/sample-modules/vitruvius-franklin/0.0.0/package.json
- prod-sample/sample-modules/vitruvius-franklin/0.0.1/package.json
- scripts/run-in-sample-modules.js
update sample modules
Ensure that the latest versions of deps are installed during integration testing.
PR integration tests.
> chore(sample-modules): update deps

- .github/workflows/on-main_release-drafter.yml
In the 5.x.x branch, reference the 5.x.x release drafter config
> chore(workflows): changes for 5.x.x

- __tests__/server/utils/pollModuleMap.spec.js
- package-lock.json
Pulled latest `main` and some unit tests from pollModuleMap are failing. After adding async/await, the errors went away
Make all unit tests pass
Ran `npm run test:unit`
> [FIX] pollModuleMap failing unit tests

- one-app-statics/package.json
> chore(package): remove deadname

- package-lock.json
- package.json
Take the latest patch to fetch-enhancers
This fixes a bug in the fetch spec implemented in 'createBrowserLikeFetch'
Unit tests
- (This PR is to 5.x.x)
- When the user specifies `credentials: 'omit'`, these headers will no-longer be sent
> fix(fetchEnhancers): take patch to fetch-enhancers (v5)

- package-lock.json
- package.json
Take the latest patch to fetch-enhancers
This fixes a bug in the fetch spec implemented in 'createBrowserLikeFetch'
Unit tests
- (Will raise PR to 5.x.x shortly)
- When the user specifies `credentials: 'omit'`, these headers will no-longer be sent
> fix(fetchEnhancers): take patch to fetch-enhancers

- __tests__/server/ssrServer.spec.js
- src/server/ssrServer.js
Migrated ssrServer to Fastify
Since we are converting ExpressJS Middlewares into Fastify Plugins, we need to refactor the ssrServer to run and consume fastify plugins
Manual, Unit Testing, Integration Test
> [REFACTOR] ssrServer to Fastify

- README.md
Fixes docker badge
Docker release badge was broken
> chore(readme): fix broken docker badge

- __tests__/server/utils/logging/fastifyPlugin.spec.js
- docs/api/modules/App-Configuration.md
- package-lock.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.3/package.json
- prod-sample/sample-modules/frank-lloyd-root/0.0.3/src/createFrankLikeFetch.js
- src/server/plugins/reactHtml/createRequestStore.js
- src/server/utils/logging/fastifyPlugin.js
Expose `request` and `reply` Fastify objects so devs can have access to fastify utility functions like `cookies`
> fix: exposing request and reply objects instead of raw

- __tests__/integration/one-app.spec.js
- prod-sample/one-app/base.env
- src/server/utils/pollModuleMap.js
Reduce the minimum poll time to 1second, keep the default 5 seconds.
speed up integration test. This change reduces the length of time by around 2 minutes
> chore(module-map-poll): reduce min time

- package-lock.json
- package.json
https://github.com/americanexpress/one-app-ducks/pull/69
> fix(memLeak): update one-app-ducks to fix memory leak

- Dockerfile
> chore(node): upgrade to node 16.20.0

- __tests__/server/utils/createCircuitBreaker.spec.js
- __tests__/server/utils/onModuleLoad.spec.jsx
- docs/api/modules/App-Configuration.md
- src/server/utils/createCircuitBreaker.js
- src/server/utils/onModuleLoad.js
> feat(circuitBreaker): configurable event loop delay percentile

- Dockerfile
Bump the node version used by One App to 16.20.1
This is a security patch
https://github.com/nodejs/node/releases/tag/v16.20.1
> The 16.x release line of Node.js is vulnerable to 4 medium severity issues, and 1 high severity issues [sic].
https://nodejs.org/en/blog/vulnerability/june-2023-security-releases
GitHub workflow will run
see #1040 for the 5.x.x branch
transparent header parsing fix, so no impact expected
> fix(node): bump node to 16.20.1 for security patches

- Dockerfile
- __tests__/server/utils/createCircuitBreaker.spec.js
- package.json
Upgrade to Node 18
Had to add the flag `--dns-result-order=ipv4first` to node because of an issue with Node 17 where `localhost` gets resolved using IPv6.
https://github.com/nodejs/node/issues/40702#issue-1042587993
Also added the `--no-experimental-fetch` because we dont want to be using an experimental feature in production. Also we already polyfill fetch.
Node 16 is EOL in September
Ran server locally, unit tests, integration tests.
> feat(node): upgrade to node 18

- .github/dependabot.yml
duplicate the settings for `main` to the n-1 branch `5.x.x`
the n-1 branch should also get alerts and updates 
From https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch it appears the `target-branch` configuration is a string and not an array?
fewer bugs via dependencies being updated more frequently
> chore(dependabot): update the 5.x.x branch

- package-lock.json
- package.json
Updated one app dev cdn to add module cache feature
one-app-dev-cdn upgrade will allow caching of modules. This will reduce one app start time.
This features reduces one app start time by loading modules from cache.
> feat(one-app-dev-cdn): update to add module cache feature

- package-lock.json
- package.json
markdown-table wasn't being used.
> chore(dev-deps): remove markdown-table

- __tests__/integration/one-app.spec.js
Increasing the log watch timeout in attempt to improve reliability when integration tests are running in GH runners
This is to improve stability of integration tests
> chore(integration-tests): increase log watch timeout

- package-lock.json
- package.json
Update bundler to the latest version
> chore(dep): bump one-app-bundler

- __tests__/integration/one-app.spec.js
Increase timeout to avoid timing issues with integration tests
> test(integration): increase log watch timeout

- package-lock.json
- package.json
Updating one-app-dev-cdn with fix for cache module.
> fix(update-package): update one-app-dev-cdn

- package-lock.json
Small audit fix
Ensure minimal vulnerabilities 
test suite.
> chore(deps): audit fix

- __tests__/server/middleware/addSecurityHeaders.spec.js
- src/server/middleware/addSecurityHeaders.js
The recommended value for this header is 2 years. We currently had it set to 6 months.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
Better security.
> feat: update strict transport security header to 2 years

- __tests__/integration/one-app.spec.js
- __tests__/server/middleware/addSecurityHeaders.spec.js
- package-lock.json
- package.json
- src/server/middleware/addSecurityHeaders.js
- src/server/ssrServer.js
The strict-transport-security header that is set in addSecurityHeaders is overridden by `helmet`.
This sets the header correctly with Helmet
strict-transport-security isn't getting set properly
Tested locally, added integration tests
> fix: correctly set strict transport security header

- package-lock.json
- package.json
updated holocron@1.9.2 which includes fix for multiple external fallbacks
> fix(holocron): update 1.9.2

- __performance__/docker-compose.yml
Set versions of images used by performance monitor.
reduce chance of breaking changes which need to be fixed for performance monitoring.
Locally by running `npm run monitor:performance`
> chore(performance): pin images

- __tests__/server/utils/devCdnFactory.spec.js
- package-lock.json
- package.json
- src/server/utils/devCdnFactory.js
proxy-agent@6 was poluting the deps with https-proxy-agent@7
Revert back to @5:
Starting one-app behind a proxy still sees errors, but only when started inside of docker.
run locally against applications behind a proxy
> fix(deps): revert proxy agent

- __tests__/server/utils/devCdnFactory.spec.js
- package-lock.json
- package.json
- src/server/utils/devCdnFactory.js
Update proxy agent to v6
Unit tests and creating a local docker image for one-app-runner
> feat(proxyagent): update proxy agent

- __tests__/client/prerender.spec.js
- package-lock.json
- package.json
- src/client/initClient.jsx
- src/client/prerender.js
Provide server state to react redux provider to for react hydration.
https://react-redux.js.org/api/provider#react-18-ssr-hydration
> feat(initclient): use serverState for hydration

- README.md
Add notice to readme that One App is InnerSource
Prep for archival
N/A
Going forward updates will only be available internally
> docs(readme): add innersource notice
